<?php

declare(strict_types=1);

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

final class CountrySeeder extends Seeder
{
    public function run(): void
    {
        DB::table('country_isos')->truncate();
        DB::statement("INSERT INTO `country_isos` (`code`, `name`, `iso3`, `full_name`) VALUES
  ('AF', 'Afghanistan', 'AFG', 'Islamic Republic of Afghanistan'),
  ('AX', 'Åland Islands', 'ALA', 'Åland Islands'),
  ('AL', 'Albania', 'ALB', 'Republic of Albania'),
  ('DZ', 'Algeria', 'DZA', 'Peoples Democratic Republic of Algeria'),
  ('AS', 'American Samoa', 'ASM', 'American Samoa'),
  ('AD', 'Andorra', 'AND', 'Principality of Andorra'),
  ('AO', 'Angola', 'AGO', 'Republic of Angola'),
  ('AI', 'Anguilla', 'AIA', 'Anguilla'),
  ('AQ', 'Antarctica', 'ATA', 'Antarctica (the territory South of 60 deg S)'),
  ('AG', 'Antigua and Barbuda', 'ATG', 'Antigua and Barbuda'),
  ('AR', 'Argentina', 'ARG', 'Argentine Republic'),
  ('AM', 'Armenia', 'ARM', 'Republic of Armenia'),
  ('AW', 'Aruba', 'ABW', 'Aruba'),
  ('AU', 'Australia', 'AUS', 'Commonwealth of Australia'),
  ('AT', 'Austria', 'AUT', 'Republic of Austria'),
  ('AZ', 'Azerbaijan', 'AZE', 'Republic of Azerbaijan'),
  ('BS', 'Bahamas', 'BHS', 'Commonwealth of the Bahamas'),
  ('BH', 'Bahrain', 'BHR', 'Kingdom of Bahrain'),
  ('BD', 'Bangladesh', 'BGD', 'Peoples Republic of Bangladesh'),
  ('BB', 'Barbados', 'BRB', 'Barbados'),
  ('BY', 'Belarus', 'BLR', 'Republic of Belarus'),
  ('BE', 'Belgium', 'BEL', 'Kingdom of Belgium'),
  ('BZ', 'Belize', 'BLZ', 'Belize'),
  ('BJ', 'Benin', 'BEN', 'Republic of Benin'),
  ('BM', 'Bermuda', 'BMU', 'Bermuda'),
  ('BT', 'Bhutan', 'BTN', 'Kingdom of Bhutan'),
  ('BO', 'Bolivia', 'BOL', 'Plurinational State of Bolivia'),
  ('BQ', 'Bonaire, Sint Eustatius and Saba', 'BES', 'Bonaire, Sint Eustatius and Saba'),
  ('BA', 'Bosnia and Herzegovina', 'BIH', 'Bosnia and Herzegovina'),
  ('BW', 'Botswana', 'BWA', 'Republic of Botswana'),
  ('BV', 'Bouvet Island (Bouvetøya)', 'BVT', 'Bouvet Island (Bouvetøya)'),
  ('BR', 'Brazil', 'BRA', 'Federative Republic of Brazil'),
  ('IO', 'British Indian Ocean Territory (Chagos Archipelago)', 'IOT', 'British Indian Ocean Territory (Chagos Archipelago)'),
  ('VG', 'British Virgin Islands', 'VGB', 'British Virgin Islands'),
  ('BN', 'Brunei Darussalam', 'BRN', 'Brunei Darussalam'),
  ('BG', 'Bulgaria', 'BGR', 'Republic of Bulgaria'),
  ('BF', 'Burkina Faso', 'BFA', 'Burkina Faso'),
  ('BI', 'Burundi', 'BDI', 'Republic of Burundi'),
  ('KH', 'Cambodia', 'KHM', 'Kingdom of Cambodia'),
  ('CM', 'Cameroon', 'CMR', 'Republic of Cameroon'),
  ('CA', 'Canada', 'CAN', 'Canada'),
  ('CV', 'Cabo Verde', 'CPV', 'Republic of Cabo Verde'),
  ('KY', 'Cayman Islands', 'CYM', 'Cayman Islands'),
  ('CF', 'Central African Republic', 'CAF', 'Central African Republic'),
  ('TD', 'Chad', 'TCD', 'Republic of Chad'),
  ('CL', 'Chile', 'CHL', 'Republic of Chile'),
  ('CN', 'China', 'CHN', 'Peoples Republic of China'),
  ('CX', 'Christmas Island', 'CXR', 'Christmas Island'),
  ('CC', 'Cocos (Keeling) Islands', 'CCK', 'Cocos (Keeling) Islands'),
  ('CO', 'Colombia', 'COL', 'Republic of Colombia'),
  ('KM', 'Comoros', 'COM', 'Union of the Comoros'),
  ('CD', 'Congo', 'COD', 'Democratic Republic of the Congo'),
  ('CG', 'Congo', 'COG', 'Republic of the Congo'),
  ('CK', 'Cook Islands', 'COK', 'Cook Islands'),
  ('CR', 'Costa Rica', 'CRI', 'Republic of Costa Rica'),
  ('CI', 'Cote d\'Ivoire', 'CIV', 'Republic of Cote d\'Ivoire'),
  ('HR', 'Croatia', 'HRV', 'Republic of Croatia'),
  ('CU', 'Cuba', 'CUB', 'Republic of Cuba'),
  ('CW', 'Curaçao', 'CUW', 'Curaçao'),
  ('CY', 'Cyprus', 'CYP', 'Republic of Cyprus'),
  ('CZ', 'Czechia', 'CZE', 'Czech Republic'),
  ('DK', 'Denmark', 'DNK', 'Kingdom of Denmark'),
  ('DJ', 'Djibouti', 'DJI', 'Republic of Djibouti'),
  ('DM', 'Dominica', 'DMA', 'Commonwealth of Dominica'),
  ('DO', 'Dominican Republic', 'DOM', 'Dominican Republic'),
  ('EC', 'Ecuador', 'ECU', 'Republic of Ecuador'),
  ('EG', 'Egypt', 'EGY', 'Arab Republic of Egypt'),
  ('SV', 'El Salvador', 'SLV', 'Republic of El Salvador'),
  ('GQ', 'Equatorial Guinea', 'GNQ', 'Republic of Equatorial Guinea'),
  ('ER', 'Eritrea', 'ERI', 'State of Eritrea'),
  ('EE', 'Estonia', 'EST', 'Republic of Estonia'),
  ('ET', 'Ethiopia', 'ETH', 'Federal Democratic Republic of Ethiopia'),
  ('FO', 'Faroe Islands', 'FRO', 'Faroe Islands'),
  ('FK', 'Falkland Islands (Malvinas)', 'FLK', 'Falkland Islands (Malvinas)'),
  ('FJ', 'Fiji', 'FJI', 'Republic of Fiji'),
  ('FI', 'Finland', 'FIN', 'Republic of Finland'),
  ('FR', 'France', 'FRA', 'French Republic'),
  ('GF', 'French Guiana', 'GUF', 'French Guiana'),
  ('PF', 'French Polynesia', 'PYF', 'French Polynesia'),
  ('TF', 'French Southern Territories', 'ATF', 'French Southern Territories'),
  ('GA', 'Gabon', 'GAB', 'Gabonese Republic'),
  ('GM', 'Gambia', 'GMB', 'Republic of the Gambia'),
  ('GE', 'Georgia', 'GEO', 'Georgia'),
  ('DE', 'Germany', 'DEU', 'Federal Republic of Germany'),
  ('GH', 'Ghana', 'GHA', 'Republic of Ghana'),
  ('GI', 'Gibraltar', 'GIB', 'Gibraltar'),
  ('GR', 'Greece', 'GRC', 'Hellenic Republic of Greece'),
  ('GL', 'Greenland', 'GRL', 'Greenland'),
  ('GD', 'Grenada', 'GRD', 'Grenada'),
  ('GP', 'Guadeloupe', 'GLP', 'Guadeloupe'),
  ('GU', 'Guam', 'GUM', 'Guam'),
  ('GT', 'Guatemala', 'GTM', 'Republic of Guatemala'),
  ('GG', 'Guernsey', 'GGY', 'Bailiwick of Guernsey'),
  ('GN', 'Guinea', 'GIN', 'Republic of Guinea'),
  ('GW', 'Guinea-Bissau', 'GNB', 'Republic of Guinea-Bissau'),
  ('GY', 'Guyana', 'GUY', 'Co-operative Republic of Guyana'),
  ('HT', 'Haiti', 'HTI', 'Republic of Haiti'),
  ('HM', 'Heard Island and McDonald Islands', 'HMD', 'Heard Island and McDonald Islands'),
  ('VA', 'Holy See (Vatican City State)', 'VAT', 'Holy See (Vatican City State)'),
  ('HN', 'Honduras', 'HND', 'Republic of Honduras'),
  ('HK', 'Hong Kong', 'HKG', 'Hong Kong Special Administrative Region of China'),
  ('HU', 'Hungary', 'HUN', 'Hungary'),
  ('IS', 'Iceland', 'ISL', 'Iceland'),
  ('IN', 'India', 'IND', 'Republic of India'),
  ('ID', 'Indonesia', 'IDN', 'Republic of Indonesia'),
  ('IR', 'Iran', 'IRN', 'Islamic Republic of Iran'),
  ('IQ', 'Iraq', 'IRQ', 'Republic of Iraq'),
  ('IE', 'Ireland', 'IRL', 'Ireland'),
  ('IM', 'Isle of Man', 'IMN', 'Isle of Man'),
  ('IL', 'Israel', 'ISR', 'State of Israel'),
  ('IT', 'Italy', 'ITA', 'Republic of Italy'),
  ('JM', 'Jamaica', 'JAM', 'Jamaica'),
  ('JP', 'Japan', 'JPN', 'Japan'),
  ('JE', 'Jersey', 'JEY', 'Bailiwick of Jersey'),
  ('JO', 'Jordan', 'JOR', 'Hashemite Kingdom of Jordan'),
  ('KZ', 'Kazakhstan', 'KAZ', 'Republic of Kazakhstan'),
  ('KE', 'Kenya', 'KEN', 'Republic of Kenya'),
  ('KI', 'Kiribati', 'KIR', 'Republic of Kiribati'),
  ('KP', 'Korea', 'PRK', 'Democratic Peoples Republic of Korea'),
  ('KR', 'Korea', 'KOR', 'Republic of Korea'),
  ('KW', 'Kuwait', 'KWT', 'State of Kuwait'),
  ('KG', 'Kyrgyz Republic', 'KGZ', 'Kyrgyz Republic'),
  ('LA', 'Lao Peoples Democratic Republic', 'LAO', 'Lao Peoples Democratic Republic'),
  ('LV', 'Latvia', 'LVA', 'Republic of Latvia'),
  ('LB', 'Lebanon', 'LBN', 'Lebanese Republic'),
  ('LS', 'Lesotho', 'LSO', 'Kingdom of Lesotho'),
  ('LR', 'Liberia', 'LBR', 'Republic of Liberia'),
  ('LY', 'Libya', 'LBY', 'State of Libya'),
  ('LI', 'Liechtenstein', 'LIE', 'Principality of Liechtenstein'),
  ('LT', 'Lithuania', 'LTU', 'Republic of Lithuania'),
  ('LU', 'Luxembourg', 'LUX', 'Grand Duchy of Luxembourg'),
  ('MO', 'Macao', 'MAC', 'Macao Special Administrative Region of China'),
  ('MG', 'Madagascar', 'MDG', 'Republic of Madagascar'),
  ('MW', 'Malawi', 'MWI', 'Republic of Malawi'),
  ('MY', 'Malaysia', 'MYS', 'Malaysia'),
  ('MV', 'Maldives', 'MDV', 'Republic of Maldives'),
  ('ML', 'Mali', 'MLI', 'Republic of Mali'),
  ('MT', 'Malta', 'MLT', 'Republic of Malta'),
  ('MH', 'Marshall Islands', 'MHL', 'Republic of the Marshall Islands'),
  ('MQ', 'Martinique', 'MTQ', 'Martinique'),
  ('MR', 'Mauritania', 'MRT', 'Islamic Republic of Mauritania'),
  ('MU', 'Mauritius', 'MUS', 'Republic of Mauritius'),
  ('YT', 'Mayotte', 'MYT', 'Mayotte'),
  ('MX', 'Mexico', 'MEX', 'United Mexican States'),
  ('FM', 'Micronesia', 'FSM', 'Federated States of Micronesia'),
  ('MD', 'Moldova', 'MDA', 'Republic of Moldova'),
  ('MC', 'Monaco', 'MCO', 'Principality of Monaco'),
  ('MN', 'Mongolia', 'MNG', 'Mongolia'),
  ('ME', 'Montenegro', 'MNE', 'Montenegro'),
  ('MS', 'Montserrat', 'MSR', 'Montserrat'),
  ('MA', 'Morocco', 'MAR', 'Kingdom of Morocco'),
  ('MZ', 'Mozambique', 'MOZ', 'Republic of Mozambique'),
  ('MM', 'Myanmar', 'MMR', 'Republic of the Union of Myanmar'),
  ('NA', 'Namibia', 'NAM', 'Republic of Namibia'),
  ('NR', 'Nauru', 'NRU', 'Republic of Nauru'),
  ('NP', 'Nepal', 'NPL', 'Nepal'),
  ('NL', 'Netherlands', 'NLD', 'Kingdom of the Netherlands'),
  ('NC', 'New Caledonia', 'NCL', 'New Caledonia'),
  ('NZ', 'New Zealand', 'NZL', 'New Zealand'),
  ('NI', 'Nicaragua', 'NIC', 'Republic of Nicaragua'),
  ('NE', 'Niger', 'NER', 'Republic of Niger'),
  ('NG', 'Nigeria', 'NGA', 'Federal Republic of Nigeria'),
  ('NU', 'Niue', 'NIU', 'Niue'),
  ('NF', 'Norfolk Island', 'NFK', 'Norfolk Island'),
  ('MK', 'North Macedonia', 'MKD', 'Republic of North Macedonia'),
  ('MP', 'Northern Mariana Islands', 'MNP', 'Commonwealth of the Northern Mariana Islands'),
  ('NO', 'Norway', 'NOR', 'Kingdom of Norway'),
  ('OM', 'Oman', 'OMN', 'Sultanate of Oman'),
  ('PK', 'Pakistan', 'PAK', 'Islamic Republic of Pakistan'),
  ('PW', 'Palau', 'PLW', 'Republic of Palau'),
  ('PS', 'Palestine', 'PSE', 'State of Palestine'),
  ('PA', 'Panama', 'PAN', 'Republic of Panama'),
  ('PG', 'Papua New Guinea', 'PNG', 'Independent State of Papua New Guinea'),
  ('PY', 'Paraguay', 'PRY', 'Republic of Paraguay'),
  ('PE', 'Peru', 'PER', 'Republic of Peru'),
  ('PH', 'Philippines', 'PHL', 'Republic of the Philippines'),
  ('PN', 'Pitcairn Islands', 'PCN', 'Pitcairn Islands'),
  ('PL', 'Poland', 'POL', 'Republic of Poland'),
  ('PT', 'Portugal', 'PRT', 'Portuguese Republic'),
  ('PR', 'Puerto Rico', 'PRI', 'Commonwealth of Puerto Rico'),
  ('QA', 'Qatar', 'QAT', 'State of Qatar'),
  ('RE', 'Réunion', 'REU', 'Réunion'),
  ('RO', 'Romania', 'ROU', 'Romania'),
  ('RU', 'Russian Federation', 'RUS', 'Russian Federation'),
  ('RW', 'Rwanda', 'RWA', 'Republic of Rwanda'),
  ('BL', 'Saint Barthélemy', 'BLM', 'Saint Barthélemy'),
  ('SH', 'Saint Helena, Ascension and Tristan da Cunha', 'SHN', 'Saint Helena, Ascension and Tristan da Cunha'),
  ('KN', 'Saint Kitts and Nevis', 'KNA', 'Federation of Saint Kitts and Nevis'),
  ('LC', 'Saint Lucia', 'LCA', 'Saint Lucia'),
  ('MF', 'Saint Martin', 'MAF', 'Saint Martin (French part)'),
  ('PM', 'Saint Pierre and Miquelon', 'SPM', 'Saint Pierre and Miquelon'),
  ('VC', 'Saint Vincent and the Grenadines', 'VCT', 'Saint Vincent and the Grenadines'),
  ('WS', 'Samoa', 'WSM', 'Independent State of Samoa'),
  ('SM', 'San Marino', 'SMR', 'Republic of San Marino'),
  ('ST', 'Sao Tome and Principe', 'STP', 'Democratic Republic of Sao Tome and Principe'),
  ('SA', 'Saudi Arabia', 'SAU', 'Kingdom of Saudi Arabia'),
  ('SN', 'Senegal', 'SEN', 'Republic of Senegal'),
  ('RS', 'Serbia', 'SRB', 'Republic of Serbia'),
  ('SC', 'Seychelles', 'SYC', 'Republic of Seychelles'),
  ('SL', 'Sierra Leone', 'SLE', 'Republic of Sierra Leone'),
  ('SG', 'Singapore', 'SGP', 'Republic of Singapore'),
  ('SX', 'Sint Maarten (Dutch part)', 'SXM', 'Sint Maarten (Dutch part)'),
  ('SK', 'Slovakia (Slovak Republic)', 'SVK', 'Slovakia (Slovak Republic)'),
  ('SI', 'Slovenia', 'SVN', 'Republic of Slovenia'),
  ('SB', 'Solomon Islands', 'SLB', 'Solomon Islands'),
  ('SO', 'Somalia', 'SOM', 'Federal Republic of Somalia'),
  ('ZA', 'South Africa', 'ZAF', 'Republic of South Africa'),
  ('GS', 'South Georgia and the South Sandwich Islands', 'SGS', 'South Georgia and the South Sandwich Islands'),
  ('SS', 'South Sudan', 'SSD', 'Republic of South Sudan'),
  ('ES', 'Spain', 'ESP', 'Kingdom of Spain'),
  ('LK', 'Sri Lanka', 'LKA', 'Democratic Socialist Republic of Sri Lanka'),
  ('SD', 'Sudan', 'SDN', 'Republic of Sudan'),
  ('SR', 'Suriname', 'SUR', 'Republic of Suriname'),
  ('SJ', 'Svalbard & Jan Mayen Islands', 'SJM', 'Svalbard & Jan Mayen Islands'),
  ('SZ', 'Eswatini', 'SWZ', 'Kingdom of Eswatini'),
  ('SE', 'Sweden', 'SWE', 'Kingdom of Sweden'),
  ('CH', 'Switzerland', 'CHE', 'Swiss Confederation'),
  ('SY', 'Syrian Arab Republic', 'SYR', 'Syrian Arab Republic'),
  ('TW', 'Taiwan', 'TWN', 'Taiwan, Province of China'),
  ('TJ', 'Tajikistan', 'TJK', 'Republic of Tajikistan'),
  ('TZ', 'Tanzania', 'TZA', 'United Republic of Tanzania'),
  ('TH', 'Thailand', 'THA', 'Kingdom of Thailand'),
  ('TL', 'Timor-Leste', 'TLS', 'Democratic Republic of Timor-Leste'),
  ('TG', 'Togo', 'TGO', 'Togolese Republic'),
  ('TK', 'Tokelau', 'TKL', 'Tokelau'),
  ('TO', 'Tonga', 'TON', 'Kingdom of Tonga'),
  ('TT', 'Trinidad and Tobago', 'TTO', 'Republic of Trinidad and Tobago'),
  ('TN', 'Tunisia', 'TUN', 'Tunisian Republic'),
  ('TR', 'Türkiye', 'TUR', 'Republic of Türkiye'),
  ('TM', 'Turkmenistan', 'TKM', 'Turkmenistan'),
  ('TC', 'Turks and Caicos Islands', 'TCA', 'Turks and Caicos Islands'),
  ('TV', 'Tuvalu', 'TUV', 'Tuvalu'),
  ('UG', 'Uganda', 'UGA', 'Republic of Uganda'),
  ('UA', 'Ukraine', 'UKR', 'Ukraine'),
  ('AE', 'United Arab Emirates', 'ARE', 'United Arab Emirates'),
  ('GB', 'United Kingdom of Great Britain and Northern Ireland', 'GBR', 'United Kingdom of Great Britain & Northern Ireland'),
  ('US', 'United States of America', 'USA', 'United States of America'),
  ('UM', 'United States Minor Outlying Islands', 'UMI','United States Minor Outlying Islands'),
  ('VI', 'United States Virgin Islands', 'VIR', 'United States Virgin Islands'),
  ('UY', 'Uruguay', 'URY', 'Eastern Republic of Uruguay'),
  ('UZ', 'Uzbekistan', 'UZB', 'Republic of Uzbekistan'),
  ('VU', 'Vanuatu', 'VUT', 'Republic of Vanuatu'),
  ('VE', 'Venezuela', 'VEN', 'Bolivarian Republic of Venezuela'),
  ('VN', 'Vietnam', 'VNM', 'Socialist Republic of Vietnam'),
  ('WF', 'Wallis and Futuna', 'WLF', 'Wallis and Futuna'),
  ('EH', 'Western Sahara', 'ESH', 'Western Sahara'),
  ('YE', 'Yemen', 'YEM', 'Yemen'),
  ('ZM', 'Zambia', 'ZMB', 'Republic of Zambia'),
  ('ZW', 'Zimbabwe', 'ZWE', 'Republic of Zimbabwe')");

    }
}
